pipeline:
  docker-supervisord:
    when:
      status: [success, failure, changed]
    image: plugins/docker:1.12
    repo: registry.eorlbruder.de/supervisord
    registry: registry.eorlbruder.de
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: .
    secrets: [docker_username, docker_password]
  notify:
    image: drillster/drone-email
    when:
      branch: master
      status: [success, failure, changed]
    secrets:
      - source: email_host
        target: email_host
      - source: email_password
        target: email_password
      - source: email
        target: plugin_from
      - source: email
        target: email_username
      - source: email
        target: email_recipients
  trigger:
    image: plugins/downstream
    server: https://drone.eorlbruder.de
    fork: true
    repositories:
      	- simple-http-server
	- cron
	- etherpad
	- mpd
	- icecast
    secrets: [ downstream_token ]
