pipeline:
  docker-supervisord:
    context: .
    dockerfile: ./Dockerfile
    image: plugins/docker:1.12
    registry: registry.eorlbruder.de
    repo: registry.eorlbruder.de/supervisord
    secrets:
    - docker_username
    - docker_password
    tags:
    - latest
  notify:
    image: drillster/drone-email
    secrets:
    - source: email_host
      target: email_host
    - source: email_password
      target: email_password
    - source: email
      target: plugin_from
    - source: email
      target: email_username
    - source: email
      target: email_recipients
    when:
      branch: master
      status:
      - failure
      - changed
  trigger:
    fork: true
    image: plugins/downstream
    repositories:
    - eorlbruders-dockerimages/simple-http-server
    - eorlbruders-dockerimages/cron
    - eorlbruders-dockerimages/etherpad
    - eorlbruders-dockerimages/mpd
    - eorlbruders-dockerimages/icecast
    secrets:
    - downstream_token
    server: https://drone.eorlbruder.de
